Document: knfoviewer
Title: Debian knfoviewer Manual
Author: <insert document author here>
Abstract: This manual describes what knfoviewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/knfoviewer/knfoviewer.sgml.gz

Format: postscript
Files: /usr/share/doc/knfoviewer/knfoviewer.ps.gz

Format: text
Files: /usr/share/doc/knfoviewer/knfoviewer.text.gz

Format: HTML
Index: /usr/share/doc/knfoviewer/html/index.html
Files: /usr/share/doc/knfoviewer/html/*.html

  
